[package]
name = "rustrouter"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
jsonpath_lib = "0.3.0"
reqwest = { version = "0.12.24", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.145"
superstruct = "0.10.0"
